[theme]
base="light"
primaryColor="#175CD3"
backgroundColor="#F6F8FB"
secondaryBackgroundColor="#FFFFFF"
textColor="#172033"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=true
maxUploadSize=50
